server:
  port: 8866
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: iLvc-novel
  datasource:
    name: isoyun
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/isoyun?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: me.ilvc.all.novel.entity


