server:
  port: 8877
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name:iLvc-blog
  datasource:
    name: db_lvcblog
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_lvcblog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: lvc159357
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: me.ilvc.all.blog.model


